
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bpjmftnvduftnwfhqohc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJwam1mdG52ZHVmdG53Zmhxb2hjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2NjExNzQsImV4cCI6MjA2MjIzNzE3NH0.mnjP9gEuH5I55RZ4gI4eJdjSpOro4mLfGRQ482PM_PI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    }
  }
);
